### PR TITLE
update chai to 2.x

### PR DESCRIPTION
**Pull request by darrrk**

### CODE REVIEW

**Comment by cybertk** [comment]
+1, **chai 2.0** does not support node 0.8

**Comment by darrrk** [comment]
temporary
npm install chai2-json-schema

**Comment by marcin-wosinek** [comment]
@darrrk thanks for the temp solution!

@Bartvds who about adding somebody as a second maintainer of the project? Project looks pretty good, and is displayed on chaijs.com and npmjs.com as obvious solution for that kind of tasks. It would be sad if it was totally abandon.

**Comment by jamsyoung** [comment]
This change was included in PR #16 which is also passing the Travis tests.

**Pull request merged**
